version: "3.9"

services:
  url-shortener-api:
    hostname: kiri.api
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 9000:80
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - url-shortener-db
  url-shortener-db:
    hostname: kiri.db
    image: postgres:16.1-alpine3.19
    ports:
      - 9001:5432
    restart: always
    environment:
      POSTGRES_USER: kiri-dev
      POSTGRES_PASSWORD: kiri-pass
      POSTGRES_DB: kiri-dev
    volumes:
      - url-shortener-db:/var/lib/postgresql/data

volumes:
  url-shortener-db:
    driver: local
